name: Workspace Automation

on:
  push:
    branches:
      - "*"

jobs:
  run-orchestrator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run orchestrator
        env:
          AWS_REGION: us-east-1
          CSV_FILE: workspaces.csv   # <--- your CSV containing workspace_id, username
        run: |
          source venv/bin/activate
          python scripts/controller.py
